version: "3.8"

services:
  db:
    image: mysql:5.7
    platform: linux/x86_64
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    hostname: db

  app:
    build:
      context: app
    environment:
      PORT: 8888
      DATABASE_URL: mysql://root@db:3306/codetest
    ports:
      - 8888:8888
    depends_on:
      - db
    volumes:
      - ./app:/app
      - /app/node_modules
